POST http://localhost:8000/exercises
Content-Type: application/json

{
  "title": "Agachamento com barra",
  "n_sections": 3,
  "n_reps": 12,
  "weight": 80.0,
  "tutorial_url": "https://www.exemplo.com/tutorial/agachamento",
  "workout_id": "679da2654a6926d21a9c70dd",
  "created_at": "2025-02-01T12:00:00",
  "updated_at": null
}