### Criar um novo plano
POST http://localhost:8000/plans
Content-Type: application/json

{
  "title": "Plano Premium",
  "description": "Acesso completo a todas as funcionalidades.",
  "type": "Mensal",
  "category": "Fitness",
  "price": 99.99,
  "seller_id": "679d9ef658e143db4df606d6"
}

### Atualização de um plano
PUT http://localhost:8000/plans/679d9f3758e143db4df606d7
Content-Type: application/json

{
  "title": "Plano Premium",
  "description": "Acesso completo a todas as funcionalidades.",
  "type": "Mensal",
  "category": "Fitness",
  "price": 99.99,
  "seller_id": "679d9e51ab0051798fd5f71e"
}

### Remoção de um plano
DELETE http://localhost:8000/plans/679d9f3758e143db4df606d7

### Busca de um plano pelo id
GET http://localhost:8000/plans/679e76cd4d48dca26484decb

### Quantidade de planos
GET http://localhost:8000/quantity/plans