### Criar um novo plano
POST http://localhost:8000/plans
Content-Type: application/json

{
  "title": "Treino Premium",
  "description": "Acesso completo a todas as funcionalidades.",
  "type": "Mensal",
  "category": "Fitness",
  "price": 99.99,
  "seller_id": "679d9ef658e143db4df606d6"
}

### Atualização de um plano
PUT http://localhost:8000/plans/67a5f991b74cf827396ee412
Content-Type: application/json

{
  "title": "Treino Super Premium",
  "description": "Acesso completo a todas as funcionalidades.",
  "type": "Anual",
  "category": "Crossfit",
  "price": 9999999.99,
  "seller_id": "679d9ef658e143db4df606d6"
}

### Remoção de um plano
DELETE http://localhost:8000/plans/679d9f3758e143db4df606d7

### Busca de um plano pelo id
GET http://localhost:8000/plans/67a797fe0bcd0d6619e9fd16

### Listagem de planos
GET http://localhost:8000/plans/?order_by=asc&sort_by=price

### Quantidade de planos
GET http://localhost:8000/quantity/plans