### Criar um novo usuário
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.dddsilva@example.com",
  "password": "SenhaSegura123",
  "cpf": "12345678901",
  "phone_number": "11987654321",
  "address": {
    "cep": "01001000",
    "street": "Avenida Paulista",
    "number": "1000",
    "neighborhood": "Bela Vista",
    "city": "São Paulo",
    "state": "SP"
  }
}

### Atualização de um usuário
PUT http://localhost:8000/users/679d9e61ab0051798fd5f720
Content-Type: application/json

{
  "name": "Eduardo Silva",
  "email": "joao.silva@example.com",
  "password": "SenhaSegura123",
  "cpf": "12345678901",
  "phone_number": "11987654321",
  "address": {
    "cep": "01001000",
    "street": "Avenida Paulista",
    "number": "1000",
    "neighborhood": "Bela Vista",
    "city": "São Paulo",
    "state": "SP"
  }
}

### Remoção de um usuário
DELETE http://localhost:8000/users/679d9e36ef936b8a7a1ecee7

### Busca de um usuário pelo id
GET http://localhost:8000/users/679d9e54ab0051798fd5f71f

### Lista usuários
GET http://localhost:8000/users/?order_by=desc&sort_by=name&limit=20

### Quantidade de usuários
GET http://localhost:8000/quantity/users

### Busca de vendedor por id
GET http://localhost:8000/seller_plans/67a79cd8a86f0c4ab98ab19d

### Listagem dos planos dos vendedores
GET http://localhost:8000/seller_plans/?sort_by=name&order_by=desc&limit=1

### Busca de comprador por id
GET http://localhost:8000/buyer_plans/67a79cd8a86f0c4ab98ab19d

### Listagem dos planos dos compradores
GET http://localhost:8000/buyer_plans/?sort_by=name&order_by=desc&limit=1