### Criar um novo usuário
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.sidlva@email.com",
  "password": "senha1234",
  "cpf": "12345678901",
  "phone_number": "+55 11 91234-5678",
  "purchased_plans": [],
  "created_plans": [],
  "created_at": "2025-01-31T12:00:00",
  "updated_at": null
}

### Atualização de um usuário
PUT http://localhost:8000/users/679d9e36ef936b8a7a1ecee7
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.sidsdfslva@email.com",
  "password": "senha1234update",
  "cpf": "12345678901",
  "phone_number": "+55 11 91234-5678",
  "purchased_plans": [],
  "created_plans": [],
  "created_at": "2025-01-31T12:00:00",
  "updated_at": null
}