POST http://localhost:8000/workouts
Content-Type: application/json

{
  "title": "Treino de Força",
  "description": "Treino de musculação para aumentar força.",
  "rest_time": 60,
  "type": "Musculação",
  "category": "Força",
  "created_at": "2025-02-01T12:00:00",
  "updated_at": null
}