### Criação de um treino
POST http://localhost:8000/workouts
Content-Type: application/json

{
  "title": "Treino de Força",
  "description": "Treino de musculação para aumentar força.",
  "rest_time": 60,
  "type": "Musculação",
  "category": "Força",
  "created_at": "2025-02-01T12:00:00",
  "updated_at": null
}

### Atualização de um treino
PUT http://localhost:8000/workouts/679da2654a6926d21a9c70de
Content-Type: application/json

{
  "title": "Treino de Força tAtualizado",
  "description": "Treino de musculação para aumentar força.",
  "rest_time": 120,
  "type": "Musculação",
  "category": "Força",
  "created_at": "2025-02-01T12:00:00",
  "updated_at": null
}

### Remoção de um treino
DELETE http://localhost:8000/workouts/679da2654a6926d21a9c70de

### Busca de um treino pelo id
GET http://localhost:8000/workouts/679e75c8eccc141407b61274